### ISSUE TITLE
Possible to use MeteorService annotation?

### ISSUE THREAD

**Issue by snimavat** [kensiprell/grails-atmosphere-meteor#51]
Is it possible to use MeteorService annotation as explained here https://github.com/Atmosphere/atmosphere-samples/blob/master/samples/meteor-chat/src/main/java/org/atmosphere/samples/chat/MeteorChat.java

can you explain how MeteorHandler artefacts are used here, i dont see u register the handler to Meteor servlet in doWithDescriptor - handler parameter in AtmoshpereMeteorConfig is not seem to be used anywhere in doWithDescriptor

**Comment by snimavat** [comment]
Okay i see, this is being done in DefaultMeteorServlet

**Comment by snimavat** [comment]
As far as i understand, we can not suspend requests received by Grails controllers, right ?

**Comment by kensiprell** [comment]
Since the Meteor API will removed in Atmosphere 3, I created this [Grails 2 sample](https://github.com/kensiprell/grails-atmosphere-sample) and this [Grails 3 sample](https://github.com/kensiprell/grails3-atmosphere-sample) as experiments to show that you don't need a plugin to use the framework. However, this is as far as I got. 

I had problems trying to use a Grails service in the normal manner after I'd decorated it with Atmosphere annotations, i.e., I couldn't get Grails DI to work at all. If I were you, I'd try [this plugin](https://github.com/zyro23/grails-spring-websocket) since it's Spring ready by default.
