### ISSUE TITLE
Broadcaster are not stored in Meteor doGet properly.

### ISSUE THREAD

**Issue by confile** [kensiprell/grails-atmosphere-meteor#58]
Reffering to this file: https://github.com/kensiprell/grails-atmosphere-meteor/blob/0d80589efcb431d2d69e1e451896bf32f7f90a67/src/templates/artifacts/MeteorHandler.groovy

In doGet you do: 

```
Broadcaster broadcaster = atmosphereMeteor.broadcasterFactory.lookup(DefaultBroadcaster.class, mapping, true)
meteor.setBroadcaster(broadcaster)
```

The problem is when I do the following in doPost you do not get the stored broadcaster back: 

```
Meteor meteor = Meteor.build(request)
println "meteor bc: "+meteor.getBroadcaster()
```

It seems that the resource still contains its default broadcaster not the one you set in doGet.

**Comment by confile** [comment]
Ah it is ``Meteor.lookup(request)``

**Comment by confile** [comment]
Meteor.lookup(request) does only work if you use websockets. When using Long Polling you have to use Meteor.build(request). What do you do in this case?

**Comment by kensiprell** [comment]
I'm not sure what you mean. I just ran the plugin's [sample app](https://github.com/kensiprell/grails-atmosphere-meteor-sample), changing these [two lines](https://github.com/kensiprell/grails-atmosphere-meteor-sample/blob/master/grails-app/views/atmosphereTest/index.gsp#L77-L78), and ran a chat session using Chrome and Firefox without any problems. I also verified that the clients were using long-polling instead of websockets.
