### ISSUE TITLE
Error loading atmosphereMeteor bean if application takes more than 60 seconds to initialize

### ISSUE THREAD

**Issue by harbdog** [kensiprell/grails-atmosphere-meteor#60]
After spending quite some time trying to figure out why my application was only failing to initialize the atmosphereMeteor bean during startup of my production (but not development) environment, I finally realized it is because I am loading a lot of data into my database that takes at least a couple or few minutes the first time it initializes (only in prod).  In development mode, I only have it load a small portion of this data to make it startup quicker. Here's some logging I got after I printed up some default values being used in the meteor bootstrap itself:

    2016-02-18 14:45:13,555 [localhost-startStop-1] INFO  conf.AtmosphereMeteorBootStrap  - Initializing atmosphereMeteor bean ....
    2016-02-18 14:45:13,590 [localhost-startStop-1] INFO  conf.AtmosphereMeteorBootStrap  - meteor delay:1000, period:2000, attempts:30
    2016-02-18 14:45:19,559 [localhost-startStop-1] INFO  conf.BootStrap  - Initializing Names/Surnames... this may take a while if first time
    Error | 2016-02-18 14:46:14,629 [Timer-0] ERROR conf.AtmosphereMeteorBootStrap$1  - AtmosphereFramework not found: atmosphereMeteor bean not initialized

If possible I'd rather not try to guess at how long is a reasonable time to load my init since a slower machine could take several minutes, maybe more (as I've seen when I've put my application on a single core OpenShift cloud intance).  Would there be a way you could improve the atmosphereMeteor bootstrap to handle longer init times automatically, maybe through an event callback?  Or perhaps a way I can set a property to prevent it from starting its timer-wait cycle until my bootstrap has finished, then calling a method directly to initialize it?

**Comment by harbdog** [comment]
For benefit of others, I've worked around it for now by overriding the plugin defaults in my Config.groovy. But I still would prefer to not have to go based on guessed numbers if that is possible

    grails {
     plugin {
      atmosphere_meteor {
        plugin {
          initializeBeans {
            delay = 10000  // milliseconds to delay initialization
            period = 5000 // milliseconds to retry initialization based on servletContext readiness (e.g. waiting finish off BootStrap activities)
            attempts = 100 // number of attempts the TimerTask will make before quitting
          }
        }
      }
     }
    }

**Comment by kensiprell** [comment]
Eric,

I thought I'd covered overriding these settings in the plugin's README, but I didn't. What you've done is not intended as a workaround but standard procedure. I struggled over several different approaches trying to get a hold of the ```AtmosphereFramework``` instance, and this is the best that I could do. If I remember correctly, the framework is loaded automatically based on what it finds on the classpath. Of course, how and when this happens depends on the container. I experimented with different ways, but the most reliable one was including it in the plugin's [AtmosphereMeteorBootStrap.groovy](https://github.com/kensiprell/grails-atmosphere-meteor/blob/master/grails-app/conf/AtmosphereMeteorBootStrap.groovy#L20-L51). 

Unfortunately, since I didn't cover it in the README, you've misunderstood the configuration settings. See the [JDK](https://docs.oracle.com/javase/7/docs/api/java/util/Timer.html#schedule%28java.util.TimerTask,%20long,%20long%29) for ```Timer()```. The ```delay``` setting determines how long it should wait before it begins executing the closure. The ```period``` setting determines the interval at which the closure repeats. For example, the [default settings](https://github.com/kensiprell/grails-atmosphere-meteor/blob/master/grails-app/conf/AtmosphereMeteorPluginConfig.groovy) have an initial delay of 1 second with the closure repeating every 2 seconds for up to a maximum of 30 repetitions. I think simply overriding the ```attempts``` setting with a higher value is all you need. I wouldn't wait 5 seconds in between tries.

I'll try and get to your other issues over the weekend.

Ken

**Comment by harbdog** [comment]
Thanks Ken, though I think my custom settings work for my scenario, I just worded my comments strangely perhaps. 

My application requires login to anywhere that would use atmosphere-meteor so I'm not worried about a 5 second wait after the webapp is finished starting.
